services:
  - type: web
    name: musiczone
    env: php
    buildCommand: composer install && npm install && npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://musiczone.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: musiczone-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: musiczone-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: musiczone-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: musiczone-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: musiczone-db
          property: password

databases:
  - name: musiczone-db
    databaseName: musiczone
    user: musiczone
    plan: free 